spring.application.name=retail
# ===================================================================
# JWT SECURITY CONFIGURATION
# In production, this value is injected by the physical server (e.g. AWS)
# ===================================================================
monate.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
monate.security.jwt.expiration-time-ms=86400000
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true